create table if not exists public.app_state (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.dad_codes (
  id bigint generated by default as identity primary key,
  keyword text not null unique,
  title text not null,
  response_text text not null,
  category text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dad_codes_category_keyword_idx
  on public.dad_codes (lower(category), lower(keyword));
